apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}-{{ .Values.DeploymentTag }}
  labels:
    app: {{ .Values.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Name }}
    spec:
      containers:
      - name: {{ .Values.Name }}
        image: ragingpuppies/{{ .Values.Name }}:{{ .Values.DeploymentTag }}
        ports:
        - containerPort: 5000