apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name }}-service--{{ .Values.DeploymentTag }}
spec:
  selector:
    app: {{ .Values.Name }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000