apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.Name }}
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: {{ .Values.ExternalPort }}